drop database if exists  hr;
create database hr;
use hr;

CREATE TABLE `emps` (
  `employee_id` int NOT NULL AUTO_INCREMENT,
  `first_name` varchar(50) DEFAULT NULL,
  `salary` int DEFAULT NULL,
  `department_id` int DEFAULT NULL,
  PRIMARY KEY (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=241 DEFAULT CHARSET=utf8;

INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (100,'Steven',24000,90);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (101,'Neena',17000,90);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (102,'Lex',17000,90);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (103,'Alexander',9000,60);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (104,'Bruce',6000,60);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (105,'David',4800,110);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (106,'Valli',4800,60);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (107,'Diana',4200,60);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (108,'Nancy',12000,100);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (109,'Daniel',9000,100);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (110,'John',8200,100);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (111,'Ismael',7700,100);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (112,'Jose Manuel',7800,100);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (113,'Luis',6900,100);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (114,'Den',11000,30);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (115,'Alexander',3100,30);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (116,'Shelli',2900,30);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (117,'Sigal',2800,30);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (118,'Guy',2600,30);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (119,'Karen',2500,30);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (120,'Matthew',8000,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (121,'Adam',8200,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (122,'Payam',7900,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (123,'Shanta',6500,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (124,'Kevin',5800,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (125,'Julia',3200,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (126,'Irene',2700,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (127,'James',2400,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (128,'Steven',2200,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (129,'Laura',3300,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (130,'Mozhe',2800,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (131,'James',2500,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (132,'TJ',2100,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (133,'Jason',3300,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (134,'Michael',2900,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (135,'Ki',2400,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (136,'Hazel',2200,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (137,'Renske',3600,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (138,'Stephen',3200,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (139,'John',2700,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (140,'Joshua',2500,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (141,'Trenna',3500,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (142,'Curtis',3100,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (143,'Randall',2600,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (144,'Peter',2500,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (145,'John',14000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (146,'Karen',13500,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (147,'Alberto',12000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (148,'Gerald',11000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (149,'Eleni',10500,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (150,'Peter',10000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (151,'David',9500,110);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (152,'Peter',9000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (153,'Christopher',8000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (154,'Nanette',7500,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (155,'Oliver',7000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (156,'Janette',10000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (157,'Patrick',9500,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (158,'Allan',9000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (159,'Lindsey',8000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (160,'Louise',7500,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (161,'Sarath',7000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (162,'Clara',10500,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (163,'Danielle',9500,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (164,'Mattea',7200,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (165,'David',6800,110);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (166,'Sundar',6400,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (167,'Amit',6200,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (168,'Lisa',11500,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (169,'Harrison',10000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (170,'Tayler',9600,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (171,'William',7400,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (172,'Elizabeth',7300,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (173,'Sundita',6100,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (174,'Ellen',11000,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (175,'Alyssa',8800,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (176,'Jonathon',8600,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (177,'Jack',8400,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (179,'Charles',6200,80);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (180,'Winston',3200,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (181,'Jean',3100,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (182,'Martha',2500,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (183,'Girard',2800,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (184,'Nandita',4200,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (185,'Alexis',4100,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (186,'Julia',3400,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (187,'Anthony',3000,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (188,'Kelly',3800,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (189,'Jennifer',3600,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (190,'Timothy',2900,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (191,'Randall',2500,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (192,'Sarah',4000,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (193,'Britney',3900,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (194,'Samuel',3200,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (195,'Vance',2800,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (196,'Alana',3100,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (197,'Kevin',3000,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (198,'Donald',2600,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (199,'Douglas',2600,50);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (200,'Jennifer',4400,10);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (201,'Michael',13000,20);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (202,'Pat',6000,20);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (203,'Susan',6500,40);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (204,'Hermann',10000,70);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (205,'Shelley',12000,110);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (206,'William',8300,110);
INSERT INTO `emps` (`employee_id`,`first_name`,`salary`,`department_id`) VALUES (240,'Uttam',45000,30);
